# Create an IAM User
AWSTemplateFormatVersion: "2010-09-09"
Description: "IAM CloudFormation template"

Resources:
  MyIAMUser:
    Type: "AWS::IAM::User"
    Properties:
      UserName: "SilasCFN"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AdministratorAccess"
    
# If i am giving admin access, just like the above example, cloudformation will show the following error: 
# "An error occurred (InsufficientCapabilitiesException) when calling the CreateStack operation: Requires capabilities : [CAPABILITY_NAMED_IAM]"
# This is asking me if i really want to confirm this operation
# If i really want to confirm the admin access then i need to run:
# aws cloudformation create-stack --stack-name "name i've gave to the stack" --template-body file://"VS filename" --capabilities CAPABILITY_NAMED_IAM

# Create an IAM Group
  MyIAMGroup:
    Type: "AWS::IAM::Group"
    Properties:
      GroupName: "SilasGroup"

# Attach User to Group
  UserToGroup:
    Type: "AWS::IAM::UserToGroupAddition"
    Properties:
      GroupName: !Ref MyIAMGroup
      Users:
        - !Ref MyIAMUser 

# IAM Role for EC"
  MyIAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal: 
              Service: ["ec2.amazonaws.com"]
            Action: ["sts:AssumeRole"]      
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/PowerUserAccess" 

# S3 Custom Policy
  MyIAMPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "CustomPolicy"
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
             - "s3:GetObject"
            Resource: "*"
      Roles:
        - !Ref MyIAMRole